name: Build & Test

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.gitignore'
      - 'README.md'

  workflow_call:
    inputs:
      dotnet-version:
        type: string
        required: true
        default: 8.0.x

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Chceckout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with: 
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build code
      run: dotnet build --no-restore

    - name: Test code
      run: dornet test --no-build --verbosity normal