name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '.gitignore'
      - 'README.md'
jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      dotnet-version: 8.0.x